[project]
name = "Counterpact-Lobby"
description = "Display a lobby preview for Counterpact."
version = "1.1"
authors = [
    { name = "Soumeh" }
]

dependencies = [
    "counterpact-watcher @ git+https://github.com/Soumeh/Counterpact-Watcher"
]